site_name: GLVisualize Documentation
theme: journal


repo_url: https://github.com/JuliaGL/GLVisualize.jl
site_description: Interactive 3D visualization with GLVisualize (Documentation).
site_author: Simon Danisch
